/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    CLAWDLimitOrder: {
      address: "0xf32db9c489273713d037312e7b689e885aa50f58",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "usdc",
              type: "address",
              internalType: "address",
            },
            {
              name: "clawd",
              type: "address",
              internalType: "address",
            },
            {
              name: "clawdUsdcPool",
              type: "address",
              internalType: "address",
            },
            {
              name: "swapRouter",
              type: "address",
              internalType: "address",
            },
            {
              name: "treasury",
              type: "address",
              internalType: "address",
            },
            {
              name: "poolFee",
              type: "uint24",
              internalType: "uint24",
            },
            {
              name: "twapWindowSecs",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "minOrderSizeUsdc",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOMINATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_ADDRESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BUYBACK_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD_USDC_POOL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IUniswapV3Pool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "KEEPER_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_ORDER_SIZE_USDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "POOL_FEE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint24",
              internalType: "uint24",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SWAP_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SWAP_ROUTER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TWAP_WINDOW_SECS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "USDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "buybackReserveUSDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelOrder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeBuyback",
          inputs: [
            {
              name: "minClawdOut",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeOrder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getOrder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CLAWDLimitOrder.Order",
              components: [
                {
                  name: "owner",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "usdcAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "limitPrice",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "minAmountOut",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "executed",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "cancelled",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orderCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orders",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limitPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minAmountOut",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "executed",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "cancelled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeOrder",
          inputs: [
            {
              name: "usdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limitPrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minAmountOut",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BuybackExecuted",
          inputs: [
            {
              name: "caller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "clawdBurned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderCancelled",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderExecuted",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "keeper",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "swapAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "keeperFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "treasuryFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "buybackFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "clawdOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderPlaced",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "limitPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "minAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 47002015,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
